### ISSUE TITLE
Las librerias mas actuales no son compatibles con el codigo

### ISSUE THREAD

**Issue by adrfrank** [huichops/kibus-world#4]
Las librerias no están referenciadas con una versión en especifico, al intentar correr el programa las librerias mas actuales de gulp no son compatibles con el codigo

**Comment by huichops** [comment]
No creí que alguien vería esto :stuck_out_tongue: 
Lamentablemente quedó incompleto y algo descuidado, y aquí solo usaba el peor algoritmo dónde solo usa la memoria el bressenham.js quedó solo como placeholder.

Acabo de corregir el gulpfile en este commit https://github.com/huichops/kibus-world/commit/40dbeb0a657282b63e96cf1b13e0dea39fa1055a, y aunque no es gran cosa espero que igual te sirva de algo.
